language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.3

before_script:
  # Load up X browser for selenium tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mysql -e 'create database ichabod_test;'
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rails g hydra:jetty
  - bundle exec rake jetty:start
  - sleep 40
  - RAILS_ENV=test bundle exec rake ichabod:load['spatial_data_repository','./ingest/test_sdr.xml']
  - RAILS_ENV=test bundle exec rake ichabod:load['lib_guides','./ingest/test_libguides.xml']
  - sleep 30


bundler_args: --without development

script: "RAILS_ENV=test bundle exec rake"

notifications:
  irc:
    channels:
      - "irc.freenode.org#libtechnyu"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
  email:
    - web.services@library.nyu.edu
