language: ruby

rvm:
  - 1.9.3
  - 2.1.0

env:
  - ICHABOD_DB_USER=mysql

before_script:
  - mysql -e 'create database ichabod_test;' -U $ICHABOD_DB_USER
  - RAILS_ENV=test bundle exec rake db:schema:load

bundler_args: --without development

script: "bundle exec rake"

notifications:
  irc:
    channels:
      - "irc.freenode.org#libtechnyu"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
  email:
    - web.services@library.nyu.edu
