type: 
  fales:    "The Fales Library & Special Collections"
  tamwag:   "Tamiment Library & Wagner Labor Archives"
  archives: "New York University Archives"
urls:
  findingaids:  "http://dlib.nyu.edu/findingaids/html/"
  endpoint_url: "https://specialcollections.library.nyu.edu/search/catalog.json"
  
