remote: &remote
  adapter: mysql2
  host: <%= (ENV["ICHABOD_HOST"] || "localhost") %>
  database: <%= (ENV["ICHABOD_DATABASE"] || "ichabod_test") %>
  username: <%= (ENV["ICHABOD_USERNAME"] || "root") %>
  password: <%= ENV["ICHABOD_PASSWORD"] %>
  encoding: utf8

development:
  <<: *remote

staging:
  <<: *remote

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
