mysql2: &mysql2
  adapter: mysql2
  encoding: utf8

remote: &remote
  <<: *mysql2
  host:     <%= (ENV['ICHABOD_DB_HOST']     || 'localhost') %>
  database: <%= (ENV['ICHABOD_DB_DATABASE'] || 'ichabod_test') %>
  username: <%= (ENV['ICHABOD_DB_USER']     || 'root') %>
  password: <%= (ENV['ICHABOD_DB_PASSWORD'] || '007love') %>

local: &local
  <<: *remote

development:
  <<: *remote

staging:
  <<: *remote

production:
  <<: *mysql2
  host:     <%= ENV['ICHABOD_DB_HOST']     %>
  database: <%= ENV['ICHABOD_DB_DATABASE'] %>
  username: <%= ENV['ICHABOD_DB_USER']     %>
  password: <%= ENV['ICHABOD_DB_PASSWORD'] %>

test: &test
  <<: *remote
  username: 'root'
  password: '007love'

cucumber:
  <<: *test
