mysql2: &mysql2
  adapter: mysql2
  encoding: utf8

remote: &remote
  <<: *mysql2
  host: <%= (ENV['ICHABOD_HOST'] || 'localhost') %>
  database: <%= (ENV['ICHABOD_DATABASE'] || 'ichabod_test') %>
  username: <%= (ENV['JENKINS']) ? ENV['ICHABOD_JENKINS_USERNAME'] : (ENV['ICHABOD_USERNAME'] || 'root') %>
  password: <%= ENV['ICHABOD_PASSWORD'] %>

local: &local
  <<: *remote

development:
  <<: *remote

staging:
  <<: *remote

test: &test
  <<: *local

cucumber:
  <<: *test
