mysql2: &mysql2
  adapter: mysql2
  encoding: utf8

remote: &remote
  <<: *mysql2
  host: <%= (ENV['ICHABOD_DB_HOST'] || 'localhost') %>
  database: <%= (ENV['ICHABOD_DB_DATABASE'] || 'ichabod_test') %>
  username: <%= (ENV['ICHABOD_DB_USER'] || 'root') %>
  password: <%= ENV['ICHABOD_DB_PASSWORD'] %>

local: &local
  <<: *mysql2
  host: 'localhost'
  database: 'ichabod_test'
  username: 'root'
  password:

development:
  <<: *local

staging:
  <<: *remote

<% if ENV['TRAVIS'] %>
test:
  <<: *mysql2
  host: 'localhost'
  username: 'mysql'
  database: 'ichabod_test'
  password:
cucumber:
  <<: *mysql2
  host: 'localhost'
  username: 'mysql'
  database: 'ichabod_test'
  password:
<% elsif ENV['JENKINS_HOME'] %>
test:
  <<: *remote
cucumber:
  <<: *remote
<% else %>
test:
  <<: *local
cucumber:
  <<: *local
<% end %>
