development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora
test: &TEST
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/fedora-test" %>
staging:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://#{ENV['SERVER_NAME']}:8983/fedora" %>
production:
  user: <%= "#{ENV['ICHABOD_FEDORA_USER']}" %>
  password: <%= "#{ENV['ICHABOD_FEDORA_PASSWORD']}" %>
  url: <%= "#{ENV['ICHABOD_FEDORA_HOST']}:#{ENV['ICHABOD_FEDORA_PORT']}/fedora" %>
cucumber:
  <<: *TEST
