terms:
  vocabulary:
    dcterms:

      # Mandatory Fields
      title:
        data_type: text
        facetable: false
        indexed: true
        mandatory: true
        multiple: true
        searchable: true
        stored: true

      # Optional Fields

      contributor:
        data_type: text
        facetable: true
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      creator:
        data_type: text
        facetable: true
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      date:
        data_type: date
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      description:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      format:
        data_type: text
        facetable: true
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      language:
        data_type: text
        facetable: true
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      publisher:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      relation:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      rights:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      subject:
        data_type: text
        facetable: true
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      type:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true

    ichabod:

      # Optional Fields

      data_provider:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      disoverable:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      geometry:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      isbn:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      location:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: false
        stored: true
      repo:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: false
        stored: true
      resource_set:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      subject_spatial:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      subject_temporal:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true

    nyucore:
      
      identifier:
        data_type: text
        facetable: false
        indexed: true
        mandatory: true
        multiple: false
        searchable: true
        stored: true
      # Optional Fields
      available:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      citation:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: false
        stored: true
      edition:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      restrictions:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: false
        searchable: false
        stored: true
      series:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      version:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: false
        stored: true
