terms:
  vocabulary:
    dcterms:
      info:
        namespace: "RDF::DC"
        uri: "http://purl.org/dc/terms/"
      # Mandatory Fields
      fields:
        title:
          data_type: text
          facetable: false
          indexed: true
          mandatory: true
          multiple: true
          searchable: true
          stored: true
          display_in_search: true
          search_order: 1
          display_in_full: true
          full_order: 1
          display_in_facet: false
        identifier:
          data_type: text
          facetable: false
          indexed: true
          mandatory: true
          multiple: false
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: false
          display_in_facet: false
        # Optional Fields
        contributor:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: false
          display_in_facet: false
        creator:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: true
          full_order: 2
          display_in_facet: true
          facet_order: 2
        date:
          data_type: date
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: false
          display_in_facet: false
        description:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: true
          full_order: 8
          display_in_facet: false
        format:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: true
          search_order: 2
          display_in_full: true
          full_order: 3
          display_in_facet: true
          facet_order: 1
        language:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: true
          search_order: 3
          display_in_full: true
          full_order: 4
          display_in_facet: true
          facet_order: 4
        publisher:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: true
          search_order: 4
          display_in_full: true
          full_order: 6
          display_in_facet: false
        relation:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: true
          full_order: 13
          display_in_facet: false
        rights:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: true
          full_order: 18
          display_in_facet: false
        subject:
          data_type: text
          facetable: true
          indexed: true 
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: false
          display_in_facet: true
          facet_order: 3
        type:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: true
          full_order: 7
          display_in_facet: false

    ichabod:
      info:
        namespace: "NYU::Ichabod::Local"
        uri: "http://library.nyu.edu/data/ichabod#"
      # Optional Fields
      fields:
        addinfolink:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: true
          full_order: 17
          display_in_facet: false
        addinfotext:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: false
          display_in_facet: false
        data_provider:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: true
          full_order: 16
          display_in_facet: false
        discoverable:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: false
          display_in_facet: false
        geometry:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: false
          display_in_facet: false
        isbn:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: true
          full_order: 5
          display_in_facet: false
        location:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: false
          stored: true
          display_in_search: false
          display_in_full: true
          full_order: 14
          display_in_facet: false
        repo:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: false
          searchable: false
          stored: true
          display_in_search: false
          display_in_full: true
          full_order: 15
          display_in_facet: false
        resource_set:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: false
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: false
          display_in_facet: false
        subject_spatial:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: false
          display_in_facet: false
        subject_temporal:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: false
          display_in_facet: false

    nyucore:
      info:
        namespace: "NYU::Nyucore"
        uri: "http://harper.bobst.nyu.edu/data/nyucore#"
        # The above uri needs to be changed to something
        # more official
      fields:
        # Optional Fields
        available:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: true
          search_order: 6
          display_in_full: true
          full_order: 12
          display_in_facet: false
        citation:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: false
          stored: true
          display_in_search: false
          display_in_full: false
          display_in_facet: false
        edition:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: false
          display_in_facet: false
        restrictions:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: false
          searchable: false
          stored: true
          display_in_search: true
          search_order: 5
          display_in_full: true
          full_order: 11
          display_in_facet: false
        series:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display_in_search: false
          display_in_full: true
          full_order: 9
          display_in_facet: false
        version:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: false
          stored: true
          display_in_search: false
          display_in_full: true
          full_order: 10
          display_in_facet: false