terms:
  vocabulary:
     dc:
       title:
         facetable: "y"
         mandatory: "y"
         occurence: 1
         stored: "y"
         searchable: "y"
         data_type: String
         indexed: "y"
