terms:
  vocabulary:
    dcterms:
      identifier:
        data_type: text
        facetable: false
        indexed: true
        mandatory: true
        multiple: true
        searchable: true
        stored: true
      title:
        data_type: text
        facetable: false
        indexed: true
        mandatory: true
        multiple: true
        searchable: true
        stored: true
      creator:
        data_type: text
        facetable: true
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      contributor:
        data_type: text
        facetable: true
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      publisher:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      type: 
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      description: 
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      date: 
        data_type: date
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      format: 
        data_type: text
        facetable: true
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      language: 
        data_type: text
        facetable: true
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      relation: 
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      rights: 
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      subject: 
        data_type: text
        facetable: true
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
    ichabod:
      resource_set:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      isbn:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      disoverable:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      data_provider:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      geometry:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      subject_spatial:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      subject_temporal:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      location:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: false
        stored: true
      repo:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: false
        stored: true
      available:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      edition:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      series:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: true
        stored: true
      version:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: false
        stored: true
      citation:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: true
        searchable: false
        stored: true
      restriction:
        data_type: text
        facetable: false
        indexed: true
        mandatory: false
        multiple: false
        searchable: false
        stored: true
