development:
  gis_cataloger:
    - gis_admin
  fda_cataloger:
    - fda_admin
  afc_group:
    - afc_admin
  io_cataloger:
    - io_admin
    - ppXX
  admin_group:
    - test_admin

test:
  gis_cataloger:
    - gis_admin
  fda_cataloger:
    - fda_admin
  afc_group:
    - afc_admin
  admin_group:
    - test_admin
cucumber:
  gis_cataloger:
    - gis_admin
  fda_cataloger:
    - fda_admin
  afc_group:
    - afc_admin
  admin_group:
    - test_admin
staging:
  gis_cataloger:
    - gis_admin
    - tst520
  fda_cataloger:
    - fda_admin
    - tst521
  afc_group:
    - afc_admin
    - kdu1
    - jgp222
  admin_group:
    - test_admin
    - dl116
    - cm1090
production:
  gis_cataloger:
    - gis_admin
  afc_group:
    - kdu1
  admin_group:
    - test_admin
    - dl116
    - cm1090
