uva-only:
  - uva-only
archivist:
  - archivist1@example.com
  - ba36@nyu.edu
donor:
  - donor1@example.com
researcher:
  - researcher1@example.com
patron:
  - patron1@example.com
admin_policy_object_editor:
  - archivist1@example.com
gis_cataloger:
  - gis_admin
fda_cataloger:
  - fda_admin
admin_group:
  - test_admin
  - user@nyu.edu
