development:
  gis_cataloger:
    - gis_admin
  fda_cataloger:
    - fda_admin
  admin_group:
    - test_admin
    - ppXX
test:
  gis_cataloger:
    - gis_admin
  fda_cataloger:
    - fda_admin
  admin_group:
    - test_admin
cucumber:
  gis_cataloger:
    - gis_admin
  fda_cataloger:
    - fda_admin
  admin_group:
    - test_admin
staging:
  gis_cataloger:
    - gis_admin
    - tst520
  fda_cataloger:
    - fda_admin
    - tst521
  admin_group:
    - test_admin
    - dl116
    - cm1090
production:
  gis_cataloger:
    - gis_admin
  admin_group:
    - test_admin
    - dl116
    - cm1090
