archivist:
  - archivist1@example.com
  - archivist2@example.com
  - leland_himself@example.com
admin_policy_object_editor:
  - archivist1@example.com
donor:
  - donor1@example.com
  - leland_himself@example.com
researcher:
  - archivist1@example.com
  - researcher1@example.com
patron:
  - patron1@example.com
  - leland_himself@example.com
gis_cataloger:
  - gis_admin
fda_cataloger:
  - fda_admin
admin_group:
  - test_admin