# This is a sample config file that does not have multiple solr instances.
development:
  url: http://localhost:8983/solr/development
test: &TEST
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/test" %>
staging:
  url: <%= "http://#{ENV['STAGING_JETTY_SERVER']}:8983/solr/development" %>
cucumber:
  <<: *TEST
production:
  url: <%= (ENV['SOLR_URL'] || 'http://solr.library.edu') %>
